[package]
name = "vaultic-crypto-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa = "0.8"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
base64 = "0.21"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }

[features]
default = []
wasm = ["wasm-bindgen"]

[lib]
crate-type = ["cdylib", "rlib"]